In [1]:
import fix_yahoo_finance as yf
from tqdm import tqdm_notebook as tqdm
import time
import json
import os
from time import strftime, localtime

In [2]:
symbols = []

file = open('xetra_etf_symbols.txt','r') 
for line in file:
    symbols.append(line.rstrip())
file.close()

# symbols

In [3]:
interval = '1d'
start = '2000-01-01'

In [4]:
for symbol in tqdm(symbols):
    ticker = yf.Ticker(symbol)

    file_path = f'data\{symbol}.csv'
    file_exists = os.path.isfile(file_path)
    file_complete = False

    if file_exists:
        file_mdate = os.path.getmtime(file_path)
        if (strftime('%x', localtime(file_mdate)) == strftime('%x', localtime())):
            file_complete = True

    if not file_complete:
        data = ticker.history(interval=interval, start=start, period=None)
        data.to_csv(file_path, index='Date')
        time.sleep(1)

HBox(children=(IntProgress(value=0, max=1451), HTML(value='')))

In [23]:
for symbol in tqdm(symbols):
    ticker = yf.Ticker(symbol)
    
    file_path = f'data\{symbol}.json'
    file_exists = os.path.isfile(file_path)
    file_complete = False    
    
    if file_exists:
        file_mdate = os.path.getmtime(file_path)
        if (strftime('%x', localtime(file_mdate)) == strftime('%x', localtime())):
            file_complete = True

    if not file_complete:    
        data = ticker.info
        file = open(file_path, 'w')
        json.dump(data, file)
        file.close()
        time.sleep(1)

HBox(children=(IntProgress(value=0, max=1451), HTML(value='')))

'05/26/19'

In [2]:
msft = yf.Ticker("MSFT")

# get stock info
msft.info

{'language': 'en-US',
 'region': 'US',
 'quoteType': 'EQUITY',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'currency': 'USD',
 'shortName': 'Microsoft Corporation',
 'exchange': 'NMS',
 'marketState': 'REGULAR',
 'regularMarketPrice': 123.81,
 'regularMarketTime': 1555943397,
 'regularMarketChange': 0.4399948,
 'regularMarketOpen': 122.62,
 'regularMarketDayHigh': 123.85,
 'regularMarketDayLow': 122.61,
 'regularMarketVolume': 3604204,
 'esgPopulated': False,
 'tradeable': True,
 'market': 'us_market',
 'priceHint': 2,
 'regularMarketChangePercent': 0.3566465,
 'regularMarketDayRange': '122.61 - 123.85',
 'regularMarketPreviousClose': 121.77,
 'bid': 123.55,
 'ask': 123.56,
 'bidSize': 10,
 'askSize': 22,
 'messageBoardId': 'finmb_21835',
 'fullExchangeName': 'NasdaqGS',
 'longName': 'Microsoft Corporation',
 'financialCurrency': 'USD',
 'averageDailyVolume3Month': 25756975,
 'twoHundredDayAverageChangePercent': 0.13349962,
 'averageDailyVolume10Day': 19380280,
 'fiftyTwoWeekLowChange': 33.53,
 'fiftyTwoWeekLowChangePercent': 0.3714001,
 'fiftyTwoWeekRange': '90.28 - 123.85',
 'fiftyTwoWeekHighChange': -0.040000916,
 'fiftyTwoWeekHighChangePercent': -0.00032297874,
 'fiftyTwoWeekLow': 90.28,
 'fiftyTwoWeekHigh': 123.85,
 'dividendDate': 1560384000,
 'earningsTimestamp': 1556136000,
 'earningsTimestampStart': 1556103540,
 'earningsTimestampEnd': 1556539200,
 'trailingAnnualDividendRate': 1.76,
 'trailingPE': 28.719555,
 'trailingAnnualDividendYield': 0.014453478,
 'epsTrailingTwelveMonths': 4.311,
 'epsForward': 5.0,
 'sharesOutstanding': 7672209920,
 'bookValue': 11.991,
 'fiftyDayAverage': 117.363235,
 'fiftyDayAverageChange': 6.446762,
 'fiftyDayAverageChangePercent': 0.054929998,
 'twoHundredDayAverage': 109.22809,
 'twoHundredDayAverageChange': 14.581909,
 'marketCap': 949896282112,
 'forwardPE': 24.762,
 'priceToBook': 10.325244,
 'sourceInterval': 15,
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'exchangeDataDelayedBy': 0,
 'symbol': 'MSFT'}

In [3]:
hist = msft.history(period="max")
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1986-03-13,0.06,0.07,0.06,0.07,1031788800,0.0,0.0
1986-03-14,0.07,0.07,0.07,0.07,308160000,0.0,0.0
1986-03-17,0.07,0.07,0.07,0.07,133171200,0.0,0.0
1986-03-18,0.07,0.07,0.07,0.07,67766400,0.0,0.0
1986-03-19,0.07,0.07,0.07,0.07,47894400,0.0,0.0
1986-03-20,0.07,0.07,0.07,0.07,58435200,0.0,0.0
1986-03-21,0.07,0.07,0.07,0.07,59990400,0.0,0.0
1986-03-24,0.07,0.07,0.06,0.07,65289600,0.0,0.0
1986-03-25,0.07,0.07,0.06,0.07,32083200,0.0,0.0
1986-03-26,0.07,0.07,0.07,0.07,22752000,0.0,0.0
1986-03-27,0.07,0.07,0.07,0.07,16848000,0.0,0.0
1986-03-31,0.07,0.07,0.07,0.07,12873600,0.0,0.0
1986-04-01,0.07,0.07,0.07,0.07,11088000,0.0,0.0
1986-04-02,0.07,0.07,0.07,0.07,27014400,0.0,0.0
1986-04-03,0.07,0.07,0.07,0.07,23040000,0.0,0.0
1986-04-04,0.07,0.07,0.07,0.07,26582400,0.0,0.0
1986-04-07,0.07,0.07,0.07,0.07,16560000,0.0,0.0
1986-04-08,0.07,0.07,0.07,0.07,10252800,0.0,0.0
1986-04-09,0.07,0.07,0.07,0.07,12153600,0.0,0.0
1986-04-10,0.07,0.07,0.07,0.07,13881600,0.0,0.0
1986-04-11,0.07,0.07,0.07,0.07,17222400,0.0,0.0
1986-04-14,0.07,0.07,0.07,0.07,12153600,0.0,0.0
1986-04-15,0.07,0.07,0.07,0.07,9302400,0.0,0.0
1986-04-16,0.07,0.08,0.07,0.08,31910400,0.0,0.0
1986-04-17,0.08,0.08,0.08,0.08,22003200,0.0,0.0
1986-04-18,0.08,0.08,0.07,0.07,21628800,0.0,0.0
1986-04-21,0.07,0.07,0.07,0.07,22924800,0.0,0.0
1986-04-22,0.07,0.07,0.07,0.07,15552000,0.0,0.0
1986-04-23,0.07,0.07,0.07,0.07,15609600,0.0,0.0
1986-04-24,0.07,0.08,0.07,0.08,62352000,0.0,0.0
...,...,...,...,...,...,...,...
2019-03-11,110.99,112.95,110.98,112.83,26491600,0.0,0.0
2019-03-12,112.82,113.99,112.65,113.62,26132700,0.0,0.0
2019-03-13,114.13,115.00,113.78,114.50,35513800,0.0,0.0
2019-03-14,114.54,115.20,114.33,114.59,30763400,0.0,0.0
2019-03-15,115.34,117.25,114.59,115.91,54681100,0.0,0.0
2019-03-18,116.17,117.61,116.05,117.57,31207600,0.0,0.0
2019-03-19,118.09,118.44,116.99,117.65,37588700,0.0,0.0
2019-03-20,117.39,118.75,116.71,117.52,28113300,0.0,0.0
2019-03-21,117.14,120.82,117.09,120.22,29854400,0.0,0.0
2019-03-22,119.50,119.59,117.04,117.05,33624500,0.0,0.0
2019-03-25,116.56,118.01,116.32,117.66,27067100,0.0,0.0
2019-03-26,118.62,118.71,116.85,117.91,26097700,0.0,0.0
2019-03-27,117.88,118.21,115.52,116.77,22733400,0.0,0.0
2019-03-28,117.44,117.58,116.13,116.93,18334800,0.0,0.0
2019-03-29,118.07,118.32,116.96,117.94,25399800,0.0,0.0
2019-04-01,118.95,119.11,118.10,119.02,22789100,0.0,0.0
2019-04-02,119.06,119.48,118.52,119.19,18142300,0.0,0.0
2019-04-03,119.86,120.43,119.15,119.97,22860700,0.0,0.0
2019-04-04,120.10,120.23,118.38,119.36,20112800,0.0,0.0
2019-04-05,119.39,120.23,119.37,119.89,15826200,0.0,0.0
2019-04-08,119.81,120.02,118.64,119.93,15116200,0.0,0.0
2019-04-09,118.63,119.54,118.58,119.28,17612000,0.0,0.0
2019-04-10,119.76,120.35,119.54,120.19,16477200,0.0,0.0
2019-04-11,120.54,120.85,119.92,120.33,14209100,0.0,0.0
2019-04-12,120.64,120.98,120.37,120.95,19745100,0.0,0.0
2019-04-15,120.94,121.58,120.57,121.05,15792600,0.0,0.0
2019-04-16,121.64,121.65,120.10,120.77,14071800,0.0,0.0
2019-04-17,121.24,121.85,120.54,121.77,19300900,0.0,0.0
2019-04-18,122.19,123.52,121.30,123.37,27991000,0.0,0.0
2019-04-22,122.62,123.85,122.61,123.82,3624399,0.0,0.0

In [4]:
msft.actions

            Dividends  Stock Splits
Date
1987-09-21       0.00           2.0
1990-04-16       0.00           2.0
1991-06-27       0.00           1.5
1992-06-15       0.00           1.5
1994-05-23       0.00           2.0
1996-12-09       0.00           2.0
1998-02-23       0.00           2.0
1999-03-29       0.00           2.0
2003-02-18       0.00           2.0
2003-02-19       0.08           0.0
2003-10-15       0.16           0.0
2004-08-23       0.08           0.0
2004-11-15       0.08           0.0
2005-02-15       0.08           0.0
2005-05-16       0.08           0.0
2005-08-15       0.08           0.0
2005-11-15       0.08           0.0
2006-02-15       0.09           0.0
2006-05-15       0.09           0.0
2006-08-15       0.09           0.0
2006-11-14       0.10           0.0
2007-02-13       0.10           0.0
2007-05-15       0.10           0.0
2007-08-14       0.10           0.0
2007-11-13       0.11           0.0
2008-02-19       0.11           0.0
2008-05-13       0.11           0.0
2008-08-19       0.11           0.0
2008-11-18       0.13           0.0
2009-02-17       0.13           0.0
...               ...           ...
2011-11-15       0.20           0.0
2012-02-14       0.20           0.0
2012-05-15       0.20           0.0
2012-08-14       0.20           0.0
2012-11-13       0.23           0.0
2013-02-19       0.23           0.0
2013-05-14       0.23           0.0
2013-08-13       0.23           0.0
2013-11-19       0.28           0.0
2014-02-18       0.28           0.0
2014-05-13       0.28           0.0
2014-08-19       0.28           0.0
2014-11-18       0.31           0.0
2015-02-17       0.31           0.0
2015-05-19       0.31           0.0
2015-08-18       0.31           0.0
2015-11-17       0.36           0.0
2016-02-16       0.36           0.0
2016-05-17       0.36           0.0
2016-08-16       0.36           0.0
2016-11-15       0.39           0.0
2017-02-14       0.39           0.0
2017-05-16       0.39           0.0
2017-08-15       0.39           0.0
2017-11-15       0.42           0.0
2018-02-14       0.42           0.0
2018-05-16       0.42           0.0
2018-08-15       0.42           0.0
2018-11-14       0.46           0.0
2019-02-20       0.46           0.0

[70 rows x 2 columns]