In [1]:
symbols = []

file = open('xetra_etf_symbols.txt','r') 
for line in file:
    symbols.append(line.rstrip())
file.close()

symbols

['DBXD.DE',
 'DXSN.DE',
 'DBPD.DE',
 'DBPE.DE',
 '4BRZ.DE',
 'SMLP.DE',
 'SMLD.DE',
 'WTEB.DE',
 'WTI2.DE',
 'UEQ3.DE',
 'UBUB.DE',
 'SPY5.DE',
 'SYBX.DE',
 'UBUD.DE',
 'SYBI.DE',
 'UIQI.DE',
 'ZPRE.DE',
 'XDWY.DE',
 'OM3X.DE',
 'XQUE.DE',
 'XMDU.DE',
 'XMVE.DE',
 'XUHY.DE',
 'SPFU.DE',
 'SPFB.DE',
 'TRDE.DE',
 'OWLU.DE',
 'PSFE.DE',
 '5HED.DE',
 'XYLE.DE',
 'XZEU.DE',
 'XZMU.DE',
 'SGAJ.DE',
 'SPFA.DE',
 'FVSJ.DE',
 'OM3M.DE',
 'SPPW.DE',
 'XD9E.DE',
 'IU0E.DE',
 'AYEP.DE',
 'XDPD.DE',
 'IBCC.DE',
 'XUEK.DE',
 'XAIX.DE',
 'XMOV.DE',
 'DEAM.DE',
 'S5SD.DE',
 'S5SG.DE',
 'EDM4.DE',
 'EDMJ.DE',
 'EDMW.DE',
 'EDM6.DE',
 'EDMU.DE',
 'XDWL.DE',
 'XDWH.DE',
 'XDWF.DE',
 'XDW0.DE',
 'XDWS.DE',
 'XDWC.DE',
 'XDWU.DE',
 'XWTS.DE',
 'XDWM.DE',
 'XDWT.DE',
 'XDWI.DE',
 'XDNY.DE',
 'XGLF.DE',
 'XDNE.DE',
 'NS4E.DE',
 'XDEP.DE',
 'XMGD.DE',
 'XESQ.DE',
 'IS31.DE',
 'BCFU.DE',
 'XDGU.DE',
 'DBXW.DE',
 'DBXA.DE',
 'DBXJ.DE',
 'DBXU.DE',
 'DBXI.DE',
 'DBXS.DE',
 'DBXN.DE',
 'DBXP.DE',
 'DBXQ.DE',
 'DBXR.DE',
 'DBXB.DE',
 'DBXC.DE',
 'DBXF.DE',
 'DBXG.DE',
 'DBXH.DE',
 'DBXK.DE',
 'DBXT.DE',
 'DXSQ.DE',
 'DBXM.DE',
 'DXSB.DE',
 'DBXX.DE',
 'DBXY.DE',
 'DBXZ.DE',
 'DBX8.DE',
 'DXSC.DE',
 'DXSD.DE',
 'DXSE.DE',
 'DXSF.DE',
 'DXSG.DE',
 'DXSH.DE',
 'DXSI.DE',
 'DXSK.DE',
 'DXSL.DE',
 'DXSM.DE',
 'DBX1.DE',
 'DBX2.DE',
 'DBX3.DE',
 'DBX4.DE',
 'DBX5.DE',
 'DBX7.DE',
 'DBX9.DE',
 'DXST.DE',
 'DXSU.DE',
 'DXSV.DE',
 'DXSW.DE',
 'DXS1.DE',
 'DXSZ.DE',
 'DXS0.DE',
 'DX2D.DE',
 'DX2G.DE',
 'DXS3.DE',
 'DXS5.DE',
 'DXS6.DE',
 'DBXV.DE',
 'DXS7.DE',
 'DX2E.DE',
 'DX2I.DE',
 'DX2J.DE',
 'DX2K.DE',
 'DX2S.DE',
 'DX2X.DE',
 'DX2Z.DE',
 'DX22.DE',
 'DBZB.DE',
 'DBX0.DE',
 'DBPG.DE',
 'DBPK.DE',
 'D5BE.DE',
 'XUTD.DE',
 'D5BF.DE',
 'DBZN.DE',
 'D5BB.DE',
 'D5BC.DE',
 'D5BI.DE',
 'D5BH.DE',
 'XAIN.DE',
 'D5BG.DE',
 'XB4N.DE',
 'XB4F.DE',
 'XBAT.DE',
 'D5BL.DE',
 'D5BK.DE',
 'D5BM.DE',
 'XCS2.DE',
 'XCS3.DE',
 'XCS4.DE',
 'XCS5.DE',
 'XCS6.DE',
 'XY4P.DE',
 'XPQP.DE',
 'XESP.DE',
 'XMKA.DE',
 'OSX4.DE',
 'XGN5.DE',
 'X03B.DE',
 'X03C.DE',
 'UIMM.DE',
 'UIMP.DE',
 'UIMR.DE',
 'UIMT.DE',
 'XBAS.DE',
 'XB4A.DE',
 'XBAK.DE',
 'XBAN.DE',
 'XMK9.DE',
 'XGVD.DE',
 'XCHA.DE',
 'XDJP.DE',
 'E129.DE',
 'XBAG.DE',
 'XBAE.DE',
 'XESD.DE',
 'CGB.DE',
 'XHY1.DE',
 'XHYG.DE',
 'XIEE.DE',
 'BOC1.DE',
 'AH50.DE',
 'XUTE.DE',
 'ALQD.DE',
 'VLUU.DE',
 'LCVB.DE',
 'XSXE.DE',
 'LEEU.DE',
 'CCNV.DE',
 'XDJE.DE',
 'ECBI.DE',
 'EUII.DE',
 'PR1E.DE',
 'PR1Z.DE',
 'PR1W.DE',
 'PR1J.DE',
 'PR1U.DE',
 'PR1C.DE',
 'PR1R.DE',
 'PR1G.DE',
 'PR1S.DE',
 'DBXE.DE',
 'DXSA.DE',
 'DXSP.DE',
 'DXET.DE']

In [18]:
import fix_yahoo_finance as yf
from tqdm import tqdm_notebook as tqdm
import time
import json

In [2]:
msft = yf.Ticker("MSFT")

# get stock info
msft.info

{'language': 'en-US',
 'region': 'US',
 'quoteType': 'EQUITY',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'currency': 'USD',
 'shortName': 'Microsoft Corporation',
 'exchange': 'NMS',
 'marketState': 'REGULAR',
 'regularMarketPrice': 123.81,
 'regularMarketTime': 1555943397,
 'regularMarketChange': 0.4399948,
 'regularMarketOpen': 122.62,
 'regularMarketDayHigh': 123.85,
 'regularMarketDayLow': 122.61,
 'regularMarketVolume': 3604204,
 'esgPopulated': False,
 'tradeable': True,
 'market': 'us_market',
 'priceHint': 2,
 'regularMarketChangePercent': 0.3566465,
 'regularMarketDayRange': '122.61 - 123.85',
 'regularMarketPreviousClose': 121.77,
 'bid': 123.55,
 'ask': 123.56,
 'bidSize': 10,
 'askSize': 22,
 'messageBoardId': 'finmb_21835',
 'fullExchangeName': 'NasdaqGS',
 'longName': 'Microsoft Corporation',
 'financialCurrency': 'USD',
 'averageDailyVolume3Month': 25756975,
 'twoHundredDayAverageChangePercent': 0.13349962,
 'averageDailyVolume10Day': 19380280,
 'fiftyTwoWeekLowChange': 33.53,
 'fiftyTwoWeekLowChangePercent': 0.3714001,
 'fiftyTwoWeekRange': '90.28 - 123.85',
 'fiftyTwoWeekHighChange': -0.040000916,
 'fiftyTwoWeekHighChangePercent': -0.00032297874,
 'fiftyTwoWeekLow': 90.28,
 'fiftyTwoWeekHigh': 123.85,
 'dividendDate': 1560384000,
 'earningsTimestamp': 1556136000,
 'earningsTimestampStart': 1556103540,
 'earningsTimestampEnd': 1556539200,
 'trailingAnnualDividendRate': 1.76,
 'trailingPE': 28.719555,
 'trailingAnnualDividendYield': 0.014453478,
 'epsTrailingTwelveMonths': 4.311,
 'epsForward': 5.0,
 'sharesOutstanding': 7672209920,
 'bookValue': 11.991,
 'fiftyDayAverage': 117.363235,
 'fiftyDayAverageChange': 6.446762,
 'fiftyDayAverageChangePercent': 0.054929998,
 'twoHundredDayAverage': 109.22809,
 'twoHundredDayAverageChange': 14.581909,
 'marketCap': 949896282112,
 'forwardPE': 24.762,
 'priceToBook': 10.325244,
 'sourceInterval': 15,
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'exchangeDataDelayedBy': 0,
 'symbol': 'MSFT'}

In [3]:
hist = msft.history(period="max")
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1986-03-13,0.06,0.07,0.06,0.07,1031788800,0.0,0.0
1986-03-14,0.07,0.07,0.07,0.07,308160000,0.0,0.0
1986-03-17,0.07,0.07,0.07,0.07,133171200,0.0,0.0
1986-03-18,0.07,0.07,0.07,0.07,67766400,0.0,0.0
1986-03-19,0.07,0.07,0.07,0.07,47894400,0.0,0.0
1986-03-20,0.07,0.07,0.07,0.07,58435200,0.0,0.0
1986-03-21,0.07,0.07,0.07,0.07,59990400,0.0,0.0
1986-03-24,0.07,0.07,0.06,0.07,65289600,0.0,0.0
1986-03-25,0.07,0.07,0.06,0.07,32083200,0.0,0.0
1986-03-26,0.07,0.07,0.07,0.07,22752000,0.0,0.0
1986-03-27,0.07,0.07,0.07,0.07,16848000,0.0,0.0
1986-03-31,0.07,0.07,0.07,0.07,12873600,0.0,0.0
1986-04-01,0.07,0.07,0.07,0.07,11088000,0.0,0.0
1986-04-02,0.07,0.07,0.07,0.07,27014400,0.0,0.0
1986-04-03,0.07,0.07,0.07,0.07,23040000,0.0,0.0
1986-04-04,0.07,0.07,0.07,0.07,26582400,0.0,0.0
1986-04-07,0.07,0.07,0.07,0.07,16560000,0.0,0.0
1986-04-08,0.07,0.07,0.07,0.07,10252800,0.0,0.0
1986-04-09,0.07,0.07,0.07,0.07,12153600,0.0,0.0
1986-04-10,0.07,0.07,0.07,0.07,13881600,0.0,0.0
1986-04-11,0.07,0.07,0.07,0.07,17222400,0.0,0.0
1986-04-14,0.07,0.07,0.07,0.07,12153600,0.0,0.0
1986-04-15,0.07,0.07,0.07,0.07,9302400,0.0,0.0
1986-04-16,0.07,0.08,0.07,0.08,31910400,0.0,0.0
1986-04-17,0.08,0.08,0.08,0.08,22003200,0.0,0.0
1986-04-18,0.08,0.08,0.07,0.07,21628800,0.0,0.0
1986-04-21,0.07,0.07,0.07,0.07,22924800,0.0,0.0
1986-04-22,0.07,0.07,0.07,0.07,15552000,0.0,0.0
1986-04-23,0.07,0.07,0.07,0.07,15609600,0.0,0.0
1986-04-24,0.07,0.08,0.07,0.08,62352000,0.0,0.0
...,...,...,...,...,...,...,...
2019-03-11,110.99,112.95,110.98,112.83,26491600,0.0,0.0
2019-03-12,112.82,113.99,112.65,113.62,26132700,0.0,0.0
2019-03-13,114.13,115.00,113.78,114.50,35513800,0.0,0.0
2019-03-14,114.54,115.20,114.33,114.59,30763400,0.0,0.0
2019-03-15,115.34,117.25,114.59,115.91,54681100,0.0,0.0
2019-03-18,116.17,117.61,116.05,117.57,31207600,0.0,0.0
2019-03-19,118.09,118.44,116.99,117.65,37588700,0.0,0.0
2019-03-20,117.39,118.75,116.71,117.52,28113300,0.0,0.0
2019-03-21,117.14,120.82,117.09,120.22,29854400,0.0,0.0
2019-03-22,119.50,119.59,117.04,117.05,33624500,0.0,0.0
2019-03-25,116.56,118.01,116.32,117.66,27067100,0.0,0.0
2019-03-26,118.62,118.71,116.85,117.91,26097700,0.0,0.0
2019-03-27,117.88,118.21,115.52,116.77,22733400,0.0,0.0
2019-03-28,117.44,117.58,116.13,116.93,18334800,0.0,0.0
2019-03-29,118.07,118.32,116.96,117.94,25399800,0.0,0.0
2019-04-01,118.95,119.11,118.10,119.02,22789100,0.0,0.0
2019-04-02,119.06,119.48,118.52,119.19,18142300,0.0,0.0
2019-04-03,119.86,120.43,119.15,119.97,22860700,0.0,0.0
2019-04-04,120.10,120.23,118.38,119.36,20112800,0.0,0.0
2019-04-05,119.39,120.23,119.37,119.89,15826200,0.0,0.0
2019-04-08,119.81,120.02,118.64,119.93,15116200,0.0,0.0
2019-04-09,118.63,119.54,118.58,119.28,17612000,0.0,0.0
2019-04-10,119.76,120.35,119.54,120.19,16477200,0.0,0.0
2019-04-11,120.54,120.85,119.92,120.33,14209100,0.0,0.0
2019-04-12,120.64,120.98,120.37,120.95,19745100,0.0,0.0
2019-04-15,120.94,121.58,120.57,121.05,15792600,0.0,0.0
2019-04-16,121.64,121.65,120.10,120.77,14071800,0.0,0.0
2019-04-17,121.24,121.85,120.54,121.77,19300900,0.0,0.0
2019-04-18,122.19,123.52,121.30,123.37,27991000,0.0,0.0
2019-04-22,122.62,123.85,122.61,123.82,3624399,0.0,0.0

In [4]:
msft.actions

            Dividends  Stock Splits
Date
1987-09-21       0.00           2.0
1990-04-16       0.00           2.0
1991-06-27       0.00           1.5
1992-06-15       0.00           1.5
1994-05-23       0.00           2.0
1996-12-09       0.00           2.0
1998-02-23       0.00           2.0
1999-03-29       0.00           2.0
2003-02-18       0.00           2.0
2003-02-19       0.08           0.0
2003-10-15       0.16           0.0
2004-08-23       0.08           0.0
2004-11-15       0.08           0.0
2005-02-15       0.08           0.0
2005-05-16       0.08           0.0
2005-08-15       0.08           0.0
2005-11-15       0.08           0.0
2006-02-15       0.09           0.0
2006-05-15       0.09           0.0
2006-08-15       0.09           0.0
2006-11-14       0.10           0.0
2007-02-13       0.10           0.0
2007-05-15       0.10           0.0
2007-08-14       0.10           0.0
2007-11-13       0.11           0.0
2008-02-19       0.11           0.0
2008-05-13       0.11           0.0
2008-08-19       0.11           0.0
2008-11-18       0.13           0.0
2009-02-17       0.13           0.0
...               ...           ...
2011-11-15       0.20           0.0
2012-02-14       0.20           0.0
2012-05-15       0.20           0.0
2012-08-14       0.20           0.0
2012-11-13       0.23           0.0
2013-02-19       0.23           0.0
2013-05-14       0.23           0.0
2013-08-13       0.23           0.0
2013-11-19       0.28           0.0
2014-02-18       0.28           0.0
2014-05-13       0.28           0.0
2014-08-19       0.28           0.0
2014-11-18       0.31           0.0
2015-02-17       0.31           0.0
2015-05-19       0.31           0.0
2015-08-18       0.31           0.0
2015-11-17       0.36           0.0
2016-02-16       0.36           0.0
2016-05-17       0.36           0.0
2016-08-16       0.36           0.0
2016-11-15       0.39           0.0
2017-02-14       0.39           0.0
2017-05-16       0.39           0.0
2017-08-15       0.39           0.0
2017-11-15       0.42           0.0
2018-02-14       0.42           0.0
2018-05-16       0.42           0.0
2018-08-15       0.42           0.0
2018-11-14       0.46           0.0
2019-02-20       0.46           0.0

[70 rows x 2 columns]

In [3]:
interval = '1d'
start = '2000-01-01'

In [20]:
for symbol in tqdm(symbols):
    ticker = yf.Ticker(symbol)
    data = ticker.history(interval=interval, start=start, period=None)
    data.to_csv(f'data\{symbol}.csv', index='Date')
    time.sleep(1)

HBox(children=(IntProgress(value=0, max=5), HTML(value='')))

In [22]:
for symbol in tqdm(symbols):
    ticker = yf.Ticker(symbol)
    data = ticker.info
    file = open(f'data\{symbol}.json', 'w')
    json.dump(data, file)
    time.sleep(1)

HBox(children=(IntProgress(value=0, max=215), HTML(value='')))

In [23]:
ticker = yf.Ticker('DXSU.DE')
data = ticker.history(interval=interval, start=start, period=None)
data

              Open    High     Low   Close  Volume  Dividends  Stock Splits
Date
2008-05-14  203.08  205.08  203.08  203.08       0          0             0
2008-05-15  203.17  205.17  203.17  203.17       0          0             0
2008-05-16  205.60  205.60  205.60  205.60      20          0             0
2008-05-19  206.08  206.12  206.08  206.12      42          0             0
2008-05-20  206.10  206.30  206.10  206.30     890          0             0
2008-05-21  206.05  206.05  206.05  206.05      50          0             0
2008-05-22  206.35  206.35  205.97  205.97     214          0             0
2008-05-23  205.54  205.56  205.53  205.56     720          0             0
2008-05-26  207.00  207.00  207.00  207.00     100          0             0
2008-05-27  205.55  205.61  205.55  205.61     244          0             0
2008-05-28  205.61  205.67  205.55  205.55     104          0             0
2008-05-29  205.55  205.55  205.10  205.10     211          0             0
2008-05-30  205.19  205.19  205.19  205.19       5          0             0
2008-06-02  205.05  208.23  205.05  207.90    4098          0             0
2008-06-03  207.99  207.99  204.50  205.34    9409          0             0
2008-06-04  205.43  205.44  205.25  205.32     185          0             0
2008-06-05  204.50  205.03  204.50  204.50       0          0             0
2008-06-06  204.89  204.89  204.83  204.83      35          0             0
2008-06-09  204.99  204.99  204.99  204.99       5          0             0
2008-06-10  204.50  204.50  203.70  203.70     418          0             0
2008-06-11  203.64  203.88  203.64  203.88     598          0             0
2008-06-12  201.12  203.12  201.12  201.12       0          0             0
2008-06-13  203.12  203.12  202.56  202.56     116          0             0
2008-06-16  202.00  202.57  202.00  202.57      24          0             0
2008-06-17  200.46  202.46  200.46  200.46       0          0             0
2008-06-18  200.56  202.56  200.56  200.56       0          0             0
2008-06-19  201.00  202.62  201.00  201.00       0          0             0
2008-06-20  202.19  202.19  202.19  202.19      22          0             0
2008-06-23  199.92  201.92  199.92  199.92       0          0             0
2008-06-24  201.72  201.72  201.72  201.72      25          0             0
...            ...     ...     ...     ...     ...        ...           ...
2019-02-15  314.30  315.40  314.30  314.99     306          0             0
2019-02-18  314.85  315.25  314.63  314.85     213          0             0
2019-02-19  315.43  315.67  315.08  315.23     856          0             0
2019-02-20  315.82  315.82  314.24  314.90    3587          0             0
2019-02-21  315.36  315.64  314.53  314.69     490          0             0
2019-02-22  314.73  316.31  314.45  316.10    2218          0             0
2019-02-25  316.24  317.47  316.24  317.15     397          0             0
2019-02-26  316.50  317.13  316.08  317.13    2378          0             0
2019-02-27  316.99  317.82  316.99  317.48    1584          0             0
2019-02-28  317.62  317.62  316.65  316.67     911          0             0
2019-03-01  316.96  317.13  316.04  316.20     139          0             0
2019-03-04  315.99  316.03  315.14  315.14     760          0             0
2019-03-05  315.29  316.63  314.62  315.08     510          0             0
2019-03-06  314.54  315.74  314.54  315.74     581          0             0
2019-03-07  315.11  315.77  314.54  314.76     271          0             0
2019-03-08  314.13  314.24  313.66  314.03     300          0             0
2019-03-11  314.76  316.33  314.76  316.19    1461          0             0
2019-03-12  316.52  317.31  316.19  317.27     775          0             0
2019-03-13  317.08  317.42  316.47  317.06     957          0             0
2019-03-14  316.92  317.11  316.37  316.82     626          0             0
2019-03-15  317.16  318.41  317.16  318.23     256          0             0
2019-03-18  318.21  318.79  318.21  318.47     239          0             0
2019-03-19  318.79  319.27  318.22  318.96   17984          0             0
2019-03-20  319.13  319.13  318.02  318.02    7656          0             0
2019-03-21  321.32  321.93  320.81  321.01    1576          0             0
2019-03-22  320.89  321.19  318.66  318.95     746          0             0
2019-03-25  319.08  319.30  318.30  319.27    2823          0             0
2019-03-26  320.00  320.85  319.56  320.66     648          0             0
2019-03-27  320.72  320.72  319.05  319.05   10837          0             0
2019-04-26  320.03  320.49  319.41  319.83     694          0             0

[2616 rows x 7 columns]

In [28]:
data[data.index == '2019-04-22']

Empty DataFrame
Columns: [Open, High, Low, Close, Volume, Dividends, Stock Splits]
Index: []

In [32]:
file = open('data\DXSU.DE.json', 'r')
data = json.load(file)
name = data['longName']
name

'Xtrackers II USD Emerging Markets Bond UCITS ETF 1C - EUR Hedged'