In [2]:
import pandas as pd
import numpy as np  
from sklearn.linear_model import LinearRegression

In [3]:
path = '/Users/martin/Google Drive/data/screener/'
name = 'DX2E_FWB.csv'
df = pd.read_csv(path+name)
df

            date     open     high      low    close  volume
0     2011-09-19  19.3900  19.4450  19.2950  19.4250      -1
1     2011-09-20  19.4300  19.7000  19.3950  19.6950      -1
2     2011-09-21  19.6700  19.7300  19.4850  19.5050      -1
3     2011-09-22  19.1300  19.1500  18.7250  18.7500      -1
4     2011-09-23  18.9700  18.9700  18.4300  18.8700      -1
...          ...      ...      ...      ...      ...     ...
2051  2019-10-28  43.7375  43.7675  43.4475  43.6225      -1
2052  2019-10-29  43.5000  43.6050  43.3125  43.5200      -1
2053  2019-10-30  43.4400  43.5500  43.2925  43.4725      -1
2054  2019-10-31  43.4300  43.6250  43.2325  43.4675      -1
2055  2019-11-01  43.6850  44.1000  43.6250  43.9000      -1

[2056 rows x 6 columns]

In [20]:
def performance(series):
    X = series.index.values.reshape(-1,1)
    y = series.values.reshape(-1,1)

    regressor = LinearRegression()  
    regressor.fit(X, y)
    
    perf = regressor.coef_[0][0]
    print(perf)
    yearly = ((perf * 250) / series.iloc[-1]) *100
    return yearly

performance(df['close'])

0.010138738748985448

5.7737692192400045