In [2]:
# Imports

import pandas as pd

from tinydb import TinyDB, Query
from tinydb.storages import JSONStorage
from tinydb.middlewares import CachingMiddleware

from tqdm import tqdm_notebook as tqdm

# Create databse

In [17]:
# Column names
    # Todo: Add status id column. Contains either own status or error id from tws.
    # Todo: Add date column for when the contract was added or re added to the database. This allows updating the database by the ib website

symbol_df = pd.DataFrame(columns=['Symbol', 'Name', 'Symbol2', 'Currency', 'Exchange', 'Status'])

In [ ]:
"""
Possible status valus:
'no_data'
'data_ends:yyyy-mm-dd'
'error:error_message'
"""

In [18]:
# Exchanges

exchanges = {
    'FWB': 'ib_fwb_etfs.csv',
    'LSE': 'ib_lse_etfs.csv',
    'LSEETF': 'ib_lse-etf_etfs.csv',
    'IBIS': 'ib_xetra_etfs.csv'
}

In [19]:
# Read contracts info from file to df

for ex, file in exchanges.items():
    one_ex_data = pd.read_csv(file, delimiter=';')
    # todo: clean symbol names
    one_ex_data['Exchange'] = ex
    contracts_df = contracts_df.append(one_ex_data, ignore_index=True, sort=True)
contracts_df.describe()

,Currency,Exchange,Name,Status,Symbol,Symbol2
count,5323,5323,5323,0,5323,5323
unique,3,4,2284,0,3732,3955
top,EUR,LSE,WisdomTree US Equity Income UCITS ETF,NaN,STAW,3DES
freq,3024,1827,12,NaN,4,3

In [10]:
# Write df to CSV

contracts_df.to_csv('contracts_database.csv', sep=';')

In [23]:
# Write list to textfile

# df = contracts_database[contracts_database['Symbol']!=contracts_database['Symbol2']]
df = contracts_df.loc[contracts_df['exchange']=='fwb', 'Symbol']
symbol_list = df.tolist()

file = open('symbollist.txt', 'w+')
for symbol in symbol_list:
    file.write(symbol+'\n')
file.close()

In [ ]:
# TODO: Create development database

In [20]:
# Write to tinydb

# ----- DANGER ZONE! -----
# 
# contracts_db = TinyDB('contracts_db.json', storage=CachingMiddleware(JSONStorage))
# 
# for index, row in tqdm(contracts_df.iterrows()):
#     contracts_db.insert({'Id': index, 
#                       'Symbol': row['Symbol'], 
#                       'Name': row['Name'], 
#                       'Currency': row['Currency'], 
#                       'Exchange': row['Exchange'],
#                       'Status': 'no_data'
#                      })
# contracts_db.close()

HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))

# Modify database

In [4]:
# Update certain status values

contracts_db = TinyDB('contracts_db.json')
my_query = Query()
# contracts_db.update({'Status': 'untouched'}, 
#                  my_query.Status == "Historical Market Data Service error message:No market data permissions for SWB STK")
contracts_db.update({'Status': 'no_data'}, my_query.Status != 'bullshit')
contracts_db.close()

# Analyse database data

In [ ]:
# Qurey data from contracts database

contracts_db = TinyDB('contracts_db.json')
my_query = Query()
result = contracts_db.search(my_query.Id <= 203)
for item in result:
    print(item)
contracts_db.close()

In [ ]:
# Read all contracts data to dataframe

contracts_db = TinyDB('contracts_db.json')
data_list = str(contracts_db.all())
contracts_db.close()

data_list = data_list.replace("'", '"')
df = pd.read_json(data_list, orient='records')
df

In [4]:
# Read contracts data to df

contracts_db = TinyDB('contracts_db.json')
data_list = contracts_db.all()
contracts_db.close()

data_string = str(data_list)
data_string = data_string.replace("-'bP'", "-bP")
data_string = data_string.replace("MOODY'S", "MOODYS")
data_string = data_string.replace("'", '"')

df = pd.read_json(data_string, orient='records')
df

,Id,Symbol,Name,Currency,Exchange,Status
0,0,BNQF,Collateralized ETC on RICI Enhanced Gas Oil TR...,EUR,FWB,Market data farm connection is OK:usfarm.nj
1,1,CNB,Lyxor Euro Corporate Bond Ex Financials UCITS ETF,EUR,FWB,2019-09-29
2,2,UEF5,UBS ETF - MSCI Emerging Markets Socially Respo...,EUR,FWB,2019-09-29
3,3,GOMA,BNP Paribas Easy Barclays Euro Government Infl...,EUR,FWB,2019-09-29
4,4,X0BM,Coba ETC -2 x Platinum Daily Short Index,EUR,FWB,2019-09-29
...,...,...,...,...,...,...
5318,5318,EXX1,iShares EURO STOXX Banks 30-15 UCITS ETF DE,EUR,IBIS,Historical Market Data Service error message:N...
5319,5319,10AM,AMUNDI INDEX BARCLAYS GLOBAL AGG 500M UCITS ET...,EUR,IBIS,Historical Market Data Service error message:N...
5320,5320,X0CW,Coba ETN -15x BUNDF Daily Short,EUR,IBIS,Finished
5321,5321,X0B3,Coba ETC 3x WTI Oil Daily Long,EUR,IBIS,Finished
5322,5322,XBJJ,ETFS Long AUD Short EUR,EUR,IBIS,Finished

In [8]:
# Group by exchange

dfe = df.groupby('Exchange').count()
dfe

            Id  Symbol  Name  Currency  Status
Exchange
FWB       1349    1349  1349      1349    1349
IBIS      1266    1266  1266      1266    1266
LSE       1827    1827  1827      1827    1827
LSEETF     881     881   881       881     881

In [5]:
# Group by status

dfs = df.groupby('Status').count()
dfs

,Id,Symbol,Name,Currency,Exchange
Status,,,,,
2019-09-29,956,956,956,956,956
Finished,2807,2807,2807,2807,2807
Historical Market Data Service error message:HMDS query returned no data: 0A12@LSE Midpoint,1,1,1,1,1
Historical Market Data Service error message:HMDS query returned no data: 0A1I@LSE Midpoint,1,1,1,1,1
Historical Market Data Service error message:HMDS query returned no data: 0A1T@LSE Midpoint,1,1,1,1,1
...,...,...,...,...,...
Historical Market Data Service error message:No market data permissions for SBF STK,1,1,1,1,1
Historical Market Data Service error message:No market data permissions for SWB STK,7,7,7,7,7
Market data farm connection is OK:eufarm,1,1,1,1,1
Market data farm connection is OK:usfarm.nj,1,1,1,1,1
No security definition has been found for the request,54,54,54,54,54

In [7]:
# Group by status + exchange

dfse = df.groupby(['Exchange', 'Status']).count()
dfse

                                                              Id  Symbol  \
Exchange Status
FWB      Finished                                            375     375
         Historical Market Data Service error message:No...  962     962
         Historical Market Data Service error message:No...    2       2
         Market data farm connection is OK:usfarm              1       1
         No security definition has been found for the r...    9       9
...                                                          ...     ...
LSEETF   Historical Market Data Service error message:HM...    1       1
         Historical Market Data Service error message:No...    1       1
         Historical Market Data Service error message:No...    1       1
         Historical Market Data Service error message:No...    2       2
         Historical Market Data Service error message:No...    1       1

                                                             Name  Currency
Exchange Status
FWB      Finished                                             375       375
         Historical Market Data Service error message:No...   962       962
         Historical Market Data Service error message:No...     2         2
         Market data farm connection is OK:usfarm               1         1
         No security definition has been found for the r...     9         9
...                                                           ...       ...
LSEETF   Historical Market Data Service error message:HM...     1         1
         Historical Market Data Service error message:No...     1         1
         Historical Market Data Service error message:No...     1         1
         Historical Market Data Service error message:No...     2         2
         Historical Market Data Service error message:No...     1         1

[364 rows x 4 columns]

In [11]:
df.loc[(df['Exchange']=='LSE') & (df['Status']!='Finished')]

,Id,Symbol,Name,Currency,Exchange,Status
1354,1354,4GLD,Xetra-Gold,EUR,LSE,Historical Market Data Service error message:H...
1358,1358,0I9M,Direxion Daily Retail Bull 3X Shares,USD,LSE,Historical Market Data Service error message:H...
1361,1361,EQUA,BNP PARIBAS EASY Equity Quality Europe UCITS ETF,EUR,LSE,Historical Market Data Service error message:H...
1369,1369,JBGOUA,GAM Precious Metals - Physical Gold,USD,LSE,Historical Market Data Service error message:H...
1373,1373,E903,ComStage 1 DivDAX UCITS ETF,EUR,LSE,Historical Market Data Service error message:H...
1375,1375,OAUE,UBS ETF CH-Gold USD,EUR,LSE,Historical Market Data Service error message:H...
1376,1376,EL4S,Deka DB EUROGOV Germany 1-3 UCITS ETF,EUR,LSE,Historical Market Data Service error message:H...
1379,1379,C054,ComStage ETF FR EURO STOXX 50 UCITS ETF,EUR,LSE,Historical Market Data Service error message:H...
1380,1380,USMVD,OSSIAM US MINIMUM VARIANCE ESG NR UCITS ETF,USD,LSE,Historical Market Data Service error message:H...
1382,1382,0L0S,SPDR S&P Aerospace & Defense ETF,USD,LSE,Historical Market Data Service error message:H...
1389,1389,CAHUSA,UBS ETF-MSCI Canada UCITS ETF,USD,LSE,Historical Market Data Service error message:H...
1391,1391,AZN2,LEVERAGE SHARES 2X ASTRAZENECA,GBP,LSE,Historical Market Data Service error message:H...
1395,1395,EL4W,Deka DB EUROGOV Germany MM UCITS ETF,EUR,LSE,Historical Market Data Service error message:H...
1401,1401,5X60,ComStage ETF Commerzbank Bund-Future TR UCITS ETF,EUR,LSE,Historical Market Data Service error message:H...
1402,1402,DIUS,BNP Paribas Easy Equity Dividend US UCIITS ETF,EUR,LSE,Historical Market Data Service error message:H...
1406,1406,OSPI,UBS ETF CH-SPI CHF,EUR,LSE,Historical Market Data Service error message:H...
1411,1411,XAD1,Xtrackers Physical Gold EUR Hedged ETC,EUR,LSE,Historical Market Data Service error message:H...
1414,1414,JBPLUX,GAM Precious Metals - Physical Platinum,USD,LSE,Historical Market Data Service error message:H...
1416,1416,BP2,LEVERAGE SHARES 2X BRITISH PETROLEUM,GBP,LSE,Historical Market Data Service error message:H...
1428,1428,0VOO,Vanguard Long-Term Corporate Bond ETF,USD,LSE,Historical Market Data Service error message:H...
1430,1430,0XE0,BNP Paribas Easy EURO STOXX 50 UCITS ETF,EUR,LSE,Historical Market Data Service error message:N...
1434,1434,EXV3,iShares STOXX Europe 600 Technology UCITS ETF DE,EUR,LSE,Historical Market Data Service error message:H...
1437,1437,ACEUKD,UBS ETFs PLC - MSCI ACWI SF UCITS ETF,EUR,LSE,Historical Market Data Service error message:H...
1443,1443,UBUM,UBS Irl ETF plc - DJ Global Select Dividend UC...,EUR,LSE,Historical Market Data Service error message:H...
1445,1445,0JFI,iShares iBoxx $ Investment Grade Corporate Bon...,USD,LSE,Historical Market Data Service error message:H...
1447,1447,EL4R,Deka DB EUROGOV Germany UCITS ETF,EUR,LSE,Historical Market Data Service error message:H...
1448,1448,0A12,Invesco Ultra Short Duration ETF,USD,LSE,Historical Market Data Service error message:H...
1449,1449,JBGOEA,GAM Precious Metals - Physical Gold,EUR,LSE,Historical Market Data Service error message:H...
1452,1452,CL4,Amundi ETF Leveraged CAC 40 Daily UCITS ETF,EUR,LSE,Historical Market Data Service error message:H...
1457,1457,H410,HSBC MSCI EMERGING MARKETS UCITS ETF,EUR,LSE,Historical Market Data Service error message:H...
...,...,...,...,...,...,...
3010,3010,0JLS,iShares MSCI Russia ETF,USD,LSE,Historical Market Data Service error message:H...
3022,3022,0YLF,Invesco S&P 500 High Dividend Low Volatility ETF,USD,LSE,Historical Market Data Service error message:H...
3023,3023,X011,ComStage ETF MSCI Europe TRN UCITS ETF,EUR,LSE,Historical Market Data Service error message:H...
3027,3027,EXI5,iShares STOXX Europe 600 Real Estate UCITS ETF DE,EUR,LSE,Historical Market Data Service error message:H...
3028,3028,USEUYH,UBS Irl ETF plc - MSCI USA hedged to EUR UCITS...,EUR,LSE,Historical Market Data Service error message:H...
3032,3032,C031,ComStage ETF ATX UCITS ETF,EUR,LSE,Historical Market Data Service error message:H...
3047,3047,MAKE,Lyxor FTSE Developed Europe Infrastructure UCI...,GBP,LSE,No security definition has been found for the ...
3058,3058,SWEUAH,UBS ETF CH - MSCI Switzerland hedged to EUR,EUR,LSE,Historical Market Data Service error message:H...
3059,3059,0MNZ,iShares Euro Government Bond Capped 1.5-2.5yr ...,EUR,LSE,Historical Market Data Service error message:N...
3060,3060,VZLA,ETFS Physical Platinum,EUR,LSE,Historical Market Data Service error message:H...
3064,3064,0JH7,iShares Dow Jones U.S. ETF,USD,LSE,Historical Market Data Service error message:H...
3067,3067,0LMN,Vanguard Total World Stock ETF,USD,LSE,Historical Market Data Service error message:H...
3078,3078,RDS2,LEVERAGE SHARES 2X ROYAL DUTCH SHELL,GBP,LSE,Historical Market Data Service error message:H...
3081,3081,C072,ComStage ETF STOXX Europe 600 Oil & Gas NR UCI...,EUR,LSE,Historical Market Data Service error message:H...
3082,3082,0YIK,Invesco QQQ Trust Series 1,USD,LSE,Historical Market Data Service error message:H...
3099,3099,DXJF,WisdomTree Japan Equity UCITS ETF,EUR,LSE,Historical Market Data Service error message:H...
3104,3104,UKSRE,UBS Irl ETF plc - MSCI United Kingdom IMI Soci...,EUR,LSE,Historical Market Data Service error message:H...
3106,3106,0Y6W,UBS ETFs plc - MAP Balanced 7 SF UCITS ETF,EUR,LSE,Historical Market Data Service error message:N...
3107,3107,GY3S,ETFS 3x Daily Short DAX 30,EUR,LSE,Historical Market Data Service error message:H...
3108,3108,ULOVE,UBS Irl ETF plc - Factor MSCI USA Low Volatili...,EUR,LSE,Historical Market Data Service error message:H...
3110,3110,C079,ComStage ETF STOXX Europe 600 Utilities NR UCI...,EUR,LSE,Historical Market Data Service error message:H...
3114,3114,SBD1,SCIBETA MN EQ 3.5 USD,USD,LSE,Historical Market Data Service error message:H...
3117,3117,ZGLDHG,ZKB Gold ETF,GBP,LSE,Historical Market Data Service error message:H...
3131,3131,JBPLEX,GAM Precious Metals - Physical Platinum,EUR,LSE,Historical Market Data Service error message:H...
3139,3139,ZGLDHE,ZKB Gold ETF,EUR,LSE,Historical Market Data Service error message:H...
3141,3141,XGII,Xtrackers II Global Inflation-Linked Bond UCIT...,EUR,LSE,Historical Market Data Service error message:H...
3150,3150,UKUKD,UBS ETF MSCI United Kingdom UCITS ETF,GBP,LSE,Historical Market Data Service error message:H...
3158,3158,E908,ComStage 1 TecDAX UCITS ETF,EUR,LSE,Historical Market Data Service error message:H...
3168,3168,JBGOGX,GAM Precious Metals - Physical Gold,GBP,LSE,Historical Market Data Service error message:H...
3174,3174,ELOVU,UBS ETF-Factor MSCI EMU Low Volatility UCITS ETF,USD,LSE,Historical Market Data Service error message:H...